import { NotificationType, TemplateCategory } from '../entities/notification-template.entity';

export const notificationTemplatesSeed = [
  // ============================================================
  // BOOKING TEMPLATES
  // ============================================================
  {
    templateId: 'booking_created',
    name: 'Booking Created',
    type: NotificationType.EMAIL,
    category: TemplateCategory.BOOKING,
    subject: 'Booking Request Received - {{bookingNumber}}',
    body: 'Dear valued customer, we have received your booking request #{{bookingNumber}} for {{petName}} at {{hospitalName}}. Appointment: {{appointmentDate}} {{appointmentTime}}. Total: ₩{{amount}}. We will confirm your booking shortly.',
    htmlBody: '<h2>Booking Request Received</h2><p>Thank you for your booking request!</p><ul><li>Booking #: {{bookingNumber}}</li><li>Pet: {{petName}}</li><li>Hospital: {{hospitalName}}</li><li>Date: {{appointmentDate}} {{appointmentTime}}</li><li>Total: ₩{{amount}}</li></ul>',
    subjectKo: '예약 접수 완료 - {{bookingNumber}}',
    bodyKo: '고객님, {{petName}}의 {{hospitalName}} 예약 요청(#{{bookingNumber}})이 접수되었습니다. 예약일시: {{appointmentDate}} {{appointmentTime}}, 금액: {{amount}}원. 곧 예약 확정 안내를 드리겠습니다.',
    htmlBodyKo: '<h2>예약 접수 완료</h2><p>예약 요청이 접수되었습니다!</p><ul><li>예약번호: {{bookingNumber}}</li><li>반려동물: {{petName}}</li><li>병원: {{hospitalName}}</li><li>예약일시: {{appointmentDate}} {{appointmentTime}}</li><li>금액: {{amount}}원</li></ul>',
    requiredVariables: ['bookingNumber', 'petName', 'hospitalName', 'appointmentDate', 'appointmentTime', 'amount'],
    sampleVariables: {
      bookingNumber: 'BOOK-20240117-001',
      petName: '복돌이',
      hospitalName: '서울 동물병원',
      appointmentDate: '2024-01-20',
      appointmentTime: '14:00',
      amount: '50,000',
    },
    isActive: true,
    priority: 3,
    tags: ['booking', 'confirmation'],
    fromEmail: 'bookings@pet-to-you.com',
    fromName: 'Pet to You Bookings',
  },
  {
    templateId: 'booking_confirmation',
    name: 'Booking Confirmation',
    type: NotificationType.EMAIL,
    category: TemplateCategory.BOOKING,
    subject: 'Booking Confirmed - {{bookingNumber}}',
    body: 'Great news! Your booking #{{bookingNumber}} for {{petName}} at {{hospitalName}} is now confirmed. Appointment: {{appointmentDate}} {{appointmentTime}}. Service: {{serviceName}}. Please arrive 10 minutes early.',
    htmlBody: '<h2 style="color: #28a745;">Booking Confirmed ✓</h2><p>Your appointment is confirmed!</p><div style="border: 2px solid #28a745; padding: 15px; margin: 10px 0;"><strong>Booking Details:</strong><ul><li>Number: {{bookingNumber}}</li><li>Pet: {{petName}}</li><li>Hospital: {{hospitalName}}</li><li>Service: {{serviceName}}</li><li>Date & Time: {{appointmentDate}} {{appointmentTime}}</li></ul></div><p><strong>Important:</strong> Please arrive 10 minutes before your scheduled time.</p>',
    subjectKo: '예약 확정 - {{bookingNumber}}',
    bodyKo: '좋은 소식입니다! {{petName}}의 {{hospitalName}} 예약(#{{bookingNumber}})이 확정되었습니다. 예약일시: {{appointmentDate}} {{appointmentTime}}, 서비스: {{serviceName}}. 10분 전 도착 부탁드립니다.',
    htmlBodyKo: '<h2 style="color: #28a745;">예약 확정 ✓</h2><p>예약이 확정되었습니다!</p><div style="border: 2px solid #28a745; padding: 15px; margin: 10px 0;"><strong>예약 정보:</strong><ul><li>예약번호: {{bookingNumber}}</li><li>반려동물: {{petName}}</li><li>병원: {{hospitalName}}</li><li>서비스: {{serviceName}}</li><li>예약일시: {{appointmentDate}} {{appointmentTime}}</li></ul></div><p><strong>안내:</strong> 예약 시간 10분 전까지 도착해주세요.</p>',
    requiredVariables: ['bookingNumber', 'petName', 'hospitalName', 'serviceName', 'appointmentDate', 'appointmentTime'],
    isActive: true,
    priority: 2,
    tags: ['booking', 'confirmation'],
    fromEmail: 'bookings@pet-to-you.com',
    fromName: 'Pet to You Bookings',
  },
  {
    templateId: 'booking_reminder',
    name: 'Booking Reminder',
    type: NotificationType.SMS,
    category: TemplateCategory.BOOKING,
    subject: 'Appointment Reminder',
    body: '[Pet to You] 내일 {{appointmentTime}}에 {{petName}} 예약이 있습니다. 장소: {{hospitalName}}. 문의: 1588-0000',
    subjectKo: '예약 알림',
    bodyKo: '[Pet to You] 내일 {{appointmentTime}}에 {{petName}} 예약이 있습니다. 장소: {{hospitalName}}. 문의: 1588-0000',
    requiredVariables: ['petName', 'hospitalName', 'appointmentTime'],
    isActive: true,
    priority: 2,
    tags: ['booking', 'reminder', 'sms'],
    smsProvider: 'naver_cloud',
    maxSendsPerDay: 5,
  },

  // ============================================================
  // PAYMENT TEMPLATES
  // ============================================================
  {
    templateId: 'payment_receipt',
    name: 'Payment Receipt',
    type: NotificationType.EMAIL,
    category: TemplateCategory.PAYMENT,
    subject: 'Payment Receipt - {{paymentNumber}}',
    body: 'Thank you for your payment! Receipt #{{paymentNumber}} - Amount: ₩{{amount}}, Method: {{paymentMethod}}, Date: {{transactionDate}}. {{receiptUrl}}',
    htmlBody: '<h2>Payment Confirmation</h2><p>Your payment has been processed successfully.</p><table style="border-collapse: collapse; width: 100%;"><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>Receipt Number:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{paymentNumber}}</td></tr><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>Amount:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">₩{{amount}}</td></tr><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>Method:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{paymentMethod}}</td></tr><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>Date:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{transactionDate}}</td></tr></table><p><a href="{{receiptUrl}}" style="background: #007bff; color: white; padding: 10px 20px; text-decoration: none; display: inline-block; margin-top: 10px;">Download Receipt</a></p>',
    subjectKo: '결제 영수증 - {{paymentNumber}}',
    bodyKo: '결제가 완료되었습니다! 영수증 번호: {{paymentNumber}}, 금액: {{amount}}원, 결제수단: {{paymentMethod}}, 일시: {{transactionDate}}. {{receiptUrl}}',
    htmlBodyKo: '<h2>결제 완료</h2><p>결제가 성공적으로 처리되었습니다.</p><table style="border-collapse: collapse; width: 100%;"><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>영수증 번호:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{paymentNumber}}</td></tr><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>금액:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{amount}}원</td></tr><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>결제수단:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{paymentMethod}}</td></tr><tr><td style="border: 1px solid #ddd; padding: 8px;"><strong>일시:</strong></td><td style="border: 1px solid #ddd; padding: 8px;">{{transactionDate}}</td></tr></table><p><a href="{{receiptUrl}}" style="background: #007bff; color: white; padding: 10px 20px; text-decoration: none; display: inline-block; margin-top: 10px;">영수증 다운로드</a></p>',
    requiredVariables: ['paymentNumber', 'amount', 'paymentMethod', 'transactionDate'],
    isActive: true,
    priority: 2,
    tags: ['payment', 'receipt'],
    fromEmail: 'payments@pet-to-you.com',
    fromName: 'Pet to You Payments',
  },
  {
    templateId: 'payment_confirmation',
    name: 'Payment Confirmation SMS',
    type: NotificationType.SMS,
    category: TemplateCategory.PAYMENT,
    subject: 'Payment Confirmed',
    body: '[Pet to You] {{amount}}원 결제가 승인되었습니다. ({{paymentMethod}}) 승인번호: {{approvalNumber}}',
    subjectKo: '결제 승인',
    bodyKo: '[Pet to You] {{amount}}원 결제가 승인되었습니다. ({{paymentMethod}}) 승인번호: {{approvalNumber}}',
    requiredVariables: ['amount', 'paymentMethod'],
    isActive: true,
    priority: 2,
    tags: ['payment', 'confirmation', 'sms'],
    smsProvider: 'naver_cloud',
    maxSendsPerDay: 10,
  },

  // ============================================================
  // PUSH NOTIFICATION TEMPLATES
  // ============================================================
  {
    templateId: 'booking_notification',
    name: 'Booking Push Notification',
    type: NotificationType.PUSH,
    category: TemplateCategory.BOOKING,
    subject: '예약 확정',
    body: '{{hospitalName}} 예약이 확정되었습니다. ({{appointmentDate}})',
    subjectKo: '예약 확정',
    bodyKo: '{{hospitalName}} 예약이 확정되었습니다. ({{appointmentDate}})',
    requiredVariables: ['hospitalName', 'appointmentDate'],
    isActive: true,
    priority: 2,
    tags: ['booking', 'push'],
    pushIcon: 'https://pet-to-you.com/icons/booking.png',
    pushSound: 'default',
    pushClickAction: 'OPEN_BOOKINGS',
  },
  {
    templateId: 'payment_notification',
    name: 'Payment Push Notification',
    type: NotificationType.PUSH,
    category: TemplateCategory.PAYMENT,
    subject: '결제 완료',
    body: '{{amount}}원 결제가 완료되었습니다.',
    subjectKo: '결제 완료',
    bodyKo: '{{amount}}원 결제가 완료되었습니다.',
    requiredVariables: ['amount'],
    isActive: true,
    priority: 2,
    tags: ['payment', 'push'],
    pushIcon: 'https://pet-to-you.com/icons/payment.png',
    pushSound: 'default',
    pushClickAction: 'OPEN_PAYMENTS',
  },

  // ============================================================
  // ADOPTION TEMPLATES
  // ============================================================
  {
    templateId: 'adoption_application_submitted',
    name: 'Adoption Application Submitted',
    type: NotificationType.EMAIL,
    category: TemplateCategory.ADOPTION,
    subject: 'Adoption Application Received - {{applicationNumber}}',
    body: 'Thank you for your adoption application #{{applicationNumber}} for {{petName}} ({{petType}}). We will review your application and contact you within 3 business days.',
    subjectKo: '입양 신청 접수 - {{applicationNumber}}',
    bodyKo: '{{petName}}({{petType}}) 입양 신청(#{{applicationNumber}})이 접수되었습니다. 3영업일 내 검토 후 연락드리겠습니다.',
    requiredVariables: ['applicationNumber', 'petName', 'petType'],
    isActive: true,
    priority: 3,
    tags: ['adoption', 'application'],
    fromEmail: 'adoption@pet-to-you.com',
    fromName: 'Pet to You Adoption',
  },

  // ============================================================
  // AUTHENTICATION TEMPLATES
  // ============================================================
  {
    templateId: 'verification_code',
    name: 'Verification Code SMS',
    type: NotificationType.SMS,
    category: TemplateCategory.AUTHENTICATION,
    subject: 'Verification Code',
    body: '[Pet to You] 인증번호: {{code}} ({{expiryMinutes}}분 유효)',
    subjectKo: '인증번호',
    bodyKo: '[Pet to You] 인증번호: {{code}} ({{expiryMinutes}}분 유효)',
    requiredVariables: ['code', 'expiryMinutes'],
    isActive: true,
    priority: 1, // Highest priority
    tags: ['auth', 'verification', 'sms'],
    smsProvider: 'naver_cloud',
    maxSendsPerHour: 5,
    cooldownMinutes: 1,
  },
];
